---

name: 'build images'

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1
    
    - name: github container registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build
      uses: docker/build-push-action@v2
      with:
        context: "."
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        tags: |
          ghcr.io/tannerjfco/cups:latest